data = {      "fantastyka": [
        "Magia jest fundamentalnym elementem w świecie fantasy.",
        "Czarodzieje potrafią manipulować rzeczywistością za pomocą magii.",
        "Uczniowie akademii magii uczą się rzucania zaklęć i kontrolowania mocy.",
        "Tajemniczy artefakt zawiera w sobie starożytną magię, której nikt nie potrafiłby się przeciwstawić.",
        "Starożytna księga skrywa w sobie najpotężniejsze zaklęcia magiczne.",
        "Mistrz magii mógłby zmienić bieg historii jednym tylko gestem ręki.",
        "Wiedźma rzucała zaklęcia z wielką precyzją i skupieniem.",
        "Elfy posiadają naturalną zdolność do manipulacji magią żywiołów.",
        "Rytuał odrodzenia wymagał potężnych mocy magicznych.",
        "Proroctwo głosiło nadejście czarodzieja, który zmieni losy całego świata.",
        "Kryształ był źródłem magicznej energii dla całej cywilizacji.",
        "Czarodziejka wznosiła magiczny mur, by chronić swój lud przed najeźdźcami.",
        "Runy wyryte na starożytnym kamiennym grobowcu miały magiczną moc odstraszenia złych duchów.",
        "Teleportacja była jednym z najpotężniejszych zaklęć, jakie czarodzieje potrafili rzucać.",
        "Alternatywny wymiar krył w sobie niezliczone niebezpieczeństwa i cuda, które mogły zachwiać rzeczywistością.",
        "Artefakt był kluczem do uwięzionego wymiaru pełnego potworów i demonów.",
        "Zaklęcie zaklęło czarodzieja na wygnanie na odległą planetę.",
        "Zbroja była oczyszczona i przygotowana do walki z przerażającym wrogiem.",
        "Wróg podjął wyzwanie, by pokonać bohaterów, którzy walczyli o wolność.",
        "Podróż w czasie była największym marzeniem każdego awanturnika.",
        "Przestrzeń to granica, którą naukowcy próbowali przekroczyć od tysiącleci.",
        "Mutant posiadał zdolności do zmieniania kształtu ciała na każdy możliwy sposób.",
        "Wiedźma rzuciła przekleństwo na nieodpowiedniego miłośnika.",
        "Stwór był stworzony z czystej energii i stał się niebezpiecznym wrogiem.",
        "Równoległy świat miał istoty, które były lustrzanym odbiciem naszego własnego świata.",
        "Sfera chroniła przed niebezpieczeństwem, które mogło zbliżyć się z każdej strony.",
        "Relikwia była ukryta przez wieki, oczekując na moment swojego odkrycia.",
        "Wizja przyszłości pokazała bohaterowi, co mogłoby się stać, jeśli nie powstrzyma wroga na czas.",
        "Zakazana wiedza była przekazywana tylko nielicznym, którzy byli godni jej moc.",
        "Duch widział wszystko, co się działo w zamku, ale był związany zaklęciem na wieczność.",
        "Urok zabezpieczył bohaterów przed zbyt wielkim niebezpieczeństwem.",
        "Magiczny krąg był miejscem, w którym czarodzieje gromadzili się, by celebrować swoje najpotężniejsze zaklęcia.",
        "Talisman był symbolem szczęścia i ochrony, który nieustannie czuwał nad swoim właścicielem.",
        "Feniks był stworzeniem, które mogło odradzać się z popiołów po każdej śmierci.",
        "Smokobójca poszukiwał smoków, by uwolnić świat od ich strachu.",
        "Zamaskowany podróżował incognito, by uniknąć uwagi swoich wrogów.",
        "Ścieżka była jedynym sposobem, by dotrzeć do legendarnej Groty Przemiany.",
        "Wizjoner widział przyszłość i przygotowywał świat na nadchodzące niebezpieczeństwa.",
        "Niewidzialność pozwalała bohaterowi na uniknięcie niebezpieczeństwa w ostatniej chwili.",
        "Energetyczne pole chroniło bohaterów przed niszczącymi atakami przeciwników.",
        "Klucz był jedynym przedmiotem, który mógł otworzyć tajemne przejście do ukrytej fortecy.",
        "Pieczęć była zaklęta, by chronić tajemnice starego świata.",
        "Przemienienie przemieniło bohatera w potężne stworzenie, gotowe na walkę.",
        "Kraina była pełna magicznych stworzeń i niebezpiecznych wyzwań.",
        "Wyrocznia przepowiedziała, że jedynie bohater o czystym sercu mógłby uratować świat przed zagładą.",
        "Płomień był symbolem odrodzenia i energii, której potrzebowali bohaterowie w walce.",
        "Pradawny artefakt był zaginiony od wieków, a jego odnalezienie mogło zmienić losy królestwa.",
        "Lodowy zamek był siedzibą zimowych potworów, które rządziły lodowymi krainami.",
        "Gwiezdny rycerz bronił galaktyki przed najeźdźcami z przestrzeni kosmicznej.",
        "Chaos zapanował w królestwie, gdy zły czarownik uwolnił swoją mroczną moc.",
        "Herold rozpowszechniał wieści o nadchodzącym zagrożeniu, które zagrażało całemu świecie.",
        "Armia gotowała się do bitwy, która miała zadecydować o przyszłości ich królestwa.",
        "Golem był stworzony z kamienia i magicznych zaklęć, by chronić swoje królestwo.",
        "Lodowiec był zamieszkany przez duchy zmarłych w mroźnych południowych krainach.",
        "Tropiciel śledził ślady wrogów, by doprowadzić bohaterów do ich kryjówki.",
        "Mistrz miecza szkolił młodych wojowników, by stali się niepokonanymi rycerzami.",
        "Czarna magia była zakazana, ale zły czarownik używał jej do swoich własnych celów.",
        "Kapłan modlił się o ochronę dla swojego ludu przed niszczącym atakiem wroga.",
        "Wizytor przyszedł do królestwa, by odkryć jego tajemnice i zaklęcia.",
        "Latanie na skrzydłach byłym marzeniem, które udało się zrealizować w świecie fantastyki.",
        "Przeznaczenie bohatera było przesądzone od jego narodzin, gdyż nosił on znak przepowiedni.",
        "Tajemnica kryła się w sercu starożytnego labiryntu, w którym przetrwał tylko najmądrzejszy."    ],
        "horror": [
 
        "Zimny dreszcz przebiegł po plecach bohatera, gdy usłyszał ciche pukanie do drzwi o północy.",
        "Z ciemności wyłoniła się postać o nieokreślonym kształcie.",
        "Szum wiatru przypominał szept niewidzialnych istot.",
        "Drzwi otworzyły się samoistnie, choć nikt nie stał w pobliżu.",
        "W oknie odbiło się coś, co przypominało twarz, lecz nie była to twarz człowieka.",
        "W najgłębszej nocy rozległ się krzyk, który zamarł w powietrzu bez echa.",
        "Na ścianie pojawiły się niewytłumaczalne ślady krwi.",
        "Wszystkie lustra w domu były przykryte czarnymi welonami, chociaż nikt ich nie dotknął.",
        "W ogrodzie zauważono dziwne ślady stóp, prowadzące do starego grobu.",
        "Przez uchylone drzwi do pokoju dobiegały ciche, nieprzyjemne szepty.",
        "Cień na ścianie poruszał się niezależnie od źródła światła.",
        "Wszystkie zegary zatrzymały się dokładnie o 3:33 w nocy.",
        "Z tyłu domu, w ciemnym zakamarku ogrodu, pojawił się nagle nieznany grobowiec.",
        "Korzystając z latarki, odkryto na ścianach pisane krwią niezrozumiałe symbole.",
        "Drewniane schody skrzypiały, chociaż na nich nie było żadnej istoty.",
        "Podczas burzy, okna drżały w rytm nieprzyjemnych stukotów na zewnątrz.",
        "Stary młyn, który od lat był opuszczony, zaczął nagle pracować bez zasilania.",
        "W lustrze pojawiło się odbicie, które nie odpowiadało żadnemu z obecnych w pokoju ludzi.",
        "W starym lustrze widać było nie to, co powinno się znajdować po drugiej stronie.",
        "Wstając rano, na podłodze znaleziono ślady mokrych stóp, choć przez całą noc nie padał deszcz.",
        "Niespodziewanie na płocie pojawił się napis napisany czerwoną farbą: 'Jesteśmy tutaj.'",
        "W słuchawce telefonu usłyszano tylko szelest, chociaż numer był nieaktywny od lat.",
        "Książki w bibliotece przekładano nocami, mimo że budynek był zamknięty.",
        "W szafie odkryto stertę starych, spranych lalek, których nikt nie pamiętał, by tam zostawiał.",
        "W starej kopalni wydobywają się dziwne dźwięki, chociaż działaność górnicza została przerwana wiele lat temu.",
        "Mroczny korytarz był pełen cieni, które unosiły się wokół, grożąc atakiem.",
        "Strach zalegał w powietrzu, gdy bohaterowie weszli do opuszczonego szpitala psychiatrycznego.",
        "Wysokiej jakości dreszcze można było odczuć w całym domu, kiedy nocne stworzenie przeszyło ciszę.",
        "Ciemność była tak głęboka, że bohater nie mógł zobaczyć własnych dłoni przed sobą.",
        "Duchowny zbierał się w sobie, by stawić czoła demonowi, który nawiedzał kościół.",
        "Stary grobowiec był pełen szmerów i szeptów, które doprowadzały do szaleństwa poszukiwaczy przygód.",
        "Opuszczone miasto skrywało mroczne sekrety, które nie chciały wyjść na jaw.",
        "Wilk wył w oddali, zapowiadając nadchodzącą śmierć i zniszczenie.",
        "Drżący od strachu, bohaterzy ukryli się w ciemnym lesie, próbując uciec przed nieuchwytnym mordercą.",
        "Krwawa pełnia oświetliła krwawy trop, który prowadził do opuszczonego cmentarza.",
        "Zatrzasnął drzwi i odwrócił się, by zobaczyć oczy pełne nienawiści w ciemnym kącie pokoju.",
        "Gorąca krew spływała po rękach bohatera, gdy odkrył, że ciało, które chciał uratować, było martwe od dawna.",
        "Tajemniczy symbol był wyrzeźbiony w drzewie, zapowiadając nadejście strasznego losu.",
        "Zombiaki wyrastały z ziemi nocą, szukając świeżych ciał do zaspokojenia swojego głodu.",
        "Dusza złamana strachem, bohater uciekał przed mrocznym, nieuchwytnym duchem.",
        "Szepczące głosy nie pozwalały bohaterowi spać, przypominając mu o mrokach, które czyhały w jego umyśle.",
        "Szkielety wychodziły z grobów, by zebrać się wokół spadającego księżyca i tańczyć w szeptach starożytnych klątw.",
        "Klatka piersiowa bohatera stężała w jego piersi, gdy usłyszał, że coś chodzi na dachu nad nim.",
        "Pająki wypełniały ciemne wnętrze starego zamku, czekając tylko na to, by ugryźć niefortunnego przybysza.",
        "Zimny wiatr wiał przez opuszczony dom, przynosząc ze sobą szepty duchów, które zginęły tam lata temu.",
        "Szalony śmiech rozbrzmiewał w mroku, ale nie było nikogo, kto mógłby być jego źródłem.",
        "Pajęczyny przyciągały się do twarzy bohatera, gdy wchodził do opuszczonego bunkru.",
        "Włosy bohatera stawały dęba, gdy usłyszał, że ktoś mówi jego imię w ciszy nocy.",
        "Przemienienie było podobne do ciemnego snu, z którego nie można było się obudzić, a które zdawało się zmieniać rzeczywistość wokół.",
        "Starożytny grób ukrywał przerażające potwory, które były wolne od stuleci.",
        "Mroczny las był domem dla wilków, które polowały na niewinne dusze wędrujące w jego głąb.",
        "Przemoc waliła się z mroku, gdy bohater widział, jak jego ukochana zmienia się w coś nieodzownego.",
        "Wściekłość rozpowszechniała się w pustym domu, kiedy mrok oblewał ściany i nie można było się z nim pożegnać.",
        "Cmentarz rozpoczął swój taniec z grobami, otwierając się na strach przed zmarłymi, którzy uderzają do życia.",
        "Stalowa pięść uderzała w klatkę piersiową bohatera, gdy ciemność przynosiła ze sobą demoniczne wizje.",
        "Dziwny zapach krwi otulał duszę, gdy bohater odkrył, że wciąż żywi wewnątrz siebie.",
        "Ubrany w powłokę z pleców ciał, bohater ukrył się w ciemnym lesie, zatrzymując umarłych."],
        "Nauka": [
        "Naukowcy odkryli nowy gatunek owada w Amazonii, który ma niezwykłe właściwości mimetyczne.",
        "Teleskop kosmiczny Hubble zarejestrował niespotykaną wcześniej supernową w galaktyce NGC 4526.",
        "Eksperymenty fizyczne potwierdziły istnienie cząstek elementarnych, które były jedynie teoretycznie przewidywane.",
        "Badania genetyczne wykazały, że delfiny komunikują się za pomocą skomplikowanych sygnałów dźwiękowych.",
        "Eksploracja Marsa przez sondę Perseverance odkryła ślady minerałów, które mogą wskazywać na istnienie życia na tym czerwonym globie.",
        "Naukowcy zidentyfikowali nowy rodzaj bakterii zdolny do degradacji plastiku, co może pomóc w walce z zanieczyszczeniem środowiska.",
        "Eksperymenty z nanotechnologią pokazały, że nanorurki węglowe mają potencjał do zastosowań w przemyśle medycznym jako nośniki leków.",
        "Kwantowe komputery mogą rewolucjonizować obliczenia dzięki możliwości jednoczesnego przetwarzania ogromnych ilości danych.",
        "Inżynierowie stworzyli roboty, które mogą operować na mikroskopijnej skali, co otwiera nowe perspektywy w medycynie precyzyjnej.",
        "Studia astronomiczne wykazały, że czarna dziura w centrum Drogi Mlecznej ma masę równą milionom naszych słońc.",
        "Naukowcy opracowali nową metodę syntezowania grafenu, co może prowadzić do nowych materiałów o rewolucyjnych właściwościach.",
        "Badania nad zmianami klimatycznymi dostarczają nowych dowodów na wpływ działalności człowieka na globalne ocieplenie.",
        "Analiza danych genetycznych wykazała, że niektóre choroby genetyczne mogą być leczone za pomocą terapii genowej.",
        "Studia nad neuronami mózgu wyjaśniają mechanizmy powstawania i przetwarzania pamięci długotrwałej.",
        "Badania nad sztuczną inteligencją pokazują, że maszynowe uczenie się może być stosowane do prognozowania trendów finansowych z wysoką dokładnością.",
        "Fizycy stworzyli materiały nadprzewodzące, które mogą być kluczowe dla rozwoju nowych technologii energetycznych.",
        "Geolodzy odkryli nowy rodzaj tektonicznych płytek, które mogą wyjaśnić sejsmiczność regionu.",
        "Naukowcy zidentyfikowali nowy gatunek rośliny w Borneo, który posiada unikalne właściwości lecznicze.",
        "Eksploracja dna oceanicznego odkryła nowe formy życia, adaptowane do skrajnych warunków środowiskowych.",
        "Chemicy opracowali nową metodę oczyszczania wody, która jest bardziej efektywna od dotychczas stosowanych rozwiązań.",
        "Naukowcy odkryli nowy typ białka w komórkach ludzkich, który może mieć kluczowe znaczenie dla walki z niektórymi chorobami neurodegeneracyjnymi.",
        "Badania kosmiczne pokazały, że na powierzchni Księżyca znajdują się złoża minerałów, które mogą być wykorzystane w przyszłych misjach kosmicznych.",
        "Genetycy zidentyfikowali nową mutację genetyczną, która może być związana z odpornością na niektóre choroby zakaźne.",
        "Naukowcy odkryli nowy rodzaj płazu w tropikalnych lasach deszczowych, który wykazuje unikalne strategie przystosowawcze.",
        "Studia nad efektami zanieczyszczeń atmosferycznych wykazują, że mogą one prowadzić do zmian w układzie immunologicznym organizmów żywych.",
        "Biotechnolodzy opracowali nowe metody produkcji białek rekombinowanych, które mają zastosowanie w medycynie i przemyśle farmaceutycznym.",
        "Badania nad oddziaływaniem promieniowania słonecznego na atmosferę pokazują, że ma ono istotny wpływ na klimat Ziemi.",
        "Naukowcy opracowali nowe technologie do monitorowania poziomu zanieczyszczeń w powietrzu, co jest kluczowe dla ochrony środowiska naturalnego.",
        "Studia nad nowymi rodzajami leków antybiotycznych pokazują, że mogą one być skuteczne w leczeniu odpornych na standardowe terapie bakterii.",
        "Fizycy kwantowi osiągnęli kolejny krok ku budowie kwantowego komputera, który ma potencjał do przetwarzania danych z niezwykłą szybkością.",
        "Eksploracja głębin oceanicznych odkryła nowe gatunki ryb, które przystosowały się do życia w wysokim ciśnieniu i niskiej temperaturze.",
        "Naukowcy odkryli nowy rodzaj zjawiska fizycznego, które może prowadzić do nowych odkryć w zakresie energii odnawialnej.",
        "Badania nad ekologią ukazują, że zmiany klimatyczne mają negatywny wpływ na bioróżnorodność w lasach tropikalnych.",
        "Inżynierowie stworzyli nowe materiały kompozytowe, które są zarówno lekkie, jak i wyjątkowo wytrzymałe mechanicznie.",
        "Naukowcy wykorzystują nowe techniki mikroskopowe do obserwacji struktury komórkowej na najmniejszych skalach.",
        "Studia nad mechanizmami ewolucji pokazują, jak gatunki przystosowują się do zmieniających się warunków środowiskowych.",
        "Chemia kwantowa wyjaśnia nowe zjawiska chemiczne, które mogą mieć zastosowanie w produkcji materiałów o zaawansowanych właściwościach.",
        "Naukowcy opracowali nowe metody monitorowania i przewidywania trzęsień ziemi, co może zwiększyć bezpieczeństwo publiczne.",
        "Badania nad genomami pokazują, jak zmiany w sekwencjach DNA mogą prowadzić do różnych fenotypów organizmów.",
        "Naukowcy odkryli nowy rodzaj rośliny w ekosystemach pustynnych, które przetrwały dzięki unikalnym mechanizmom przystosowawczym.",
        "Fizycy jądrowi dokonali przełomowego odkrycia w zakresie fuzji jądrowej, co może prowadzić do bezpiecznych i czystych źródeł energii.",
        "Naukowcy wykorzystują algorytmy uczenia maszynowego do analizy dużych zbiorów danych biologicznych, co prowadzi do nowych odkryć w biologii molekularnej.",
        "Badania nad strukturą DNA ukazują, jak podwójna helisa przekazuje informacje genetyczne z pokolenia na pokolenie."],   
        "Bajka": [
        "Dawno, dawno temu, w krainie pełnej czarów i tajemnic, żył pewien młody książę.",
        "Wysoko na niebie, wśród gwiezdnych promieni, zamieszkiwała dobra czarownica, gotowa spełnić każde życzenie.",
        "W głębokim lesie, w starej chatce, mieszkała staruszka, która znała sekrety najstarszych drzew.",
        "Jednorożec biegający po łąkach miał magiczny róg, który rozjaśniał najmroczniejsze zaułki.",
        "Księżniczka, zamknięta w wieży, czekała na odważnego rycerza, który uwolni ją od czarów złego czarnoksiężnika.",
        "Wąż, który potrafił mówić, pomógł biednemu chłopcu zdobyć skarb ukryty pod korzeniami największego dębu w lesie.",
        "Dzięki pomocy małej wróżki, chłopiec przekształcił się w nieustraszonego wojownika, gotowego stawić czoła smokowi.",
        "Pod drzewem jabłoni, której owoce miały magiczną moc, mieszkała staruszka, która spełniała marzenia swoich sąsiadów.",
        "Odwaga małego krasnoludka uratowała królestwo przed zagładą, pokonując złego władcę mrocznych sił.",
        "Najmłodszy z trzech braci odkrył magiczny miecz, który dawał mu niezwykłą siłę i mądrość.",
        "Dobre wróżki, w swoich latających rydwanach, zjawiały się nagle, aby pomóc dobrym ludziom w trudnych chwilach.",
        "Klątwa, rzucona na królewnę, miała zostać złamana przez pierwszego, który dotknie złotej róży w ogrodzie pełnym cierni.",
        "W starym zamku, na wzgórzu, żył duch starego króla, który opiekował się swoim królestwem nawet po śmierci.",
        "W magicznym lustrze odzwierciedlały się marzenia, które mogły stać się rzeczywistością, jeśli tylko ktoś uwierzył w ich moc.",
        "Bajkowy świat był pełen niespodzianek i przygód, które czekały na odważnych i mądrych."
    ]  , "proza/romans": ["Zakochane oczy spotkały się przez tłum, a świat zamarł na chwilę.",
 "Pierwszy pocałunek był jak zapowiedź całego życia razem.",
 "Miłość rozkwitała pod jasnym słońcem, malując ich świat na różowo.",
 "Dłonie splatały się w milczeniu, mówiąc więcej niż tysiąc słów.",
 "Zauroczenie wypełniało powietrze, gdy ich spojrzenia się zetknęły.",
 "Zakochani gubili się w swoich uściskach, nie chcąc się nigdy rozstać.",
 "Miłość była jak niebiańska melodia, która nie znikała nawet w najciemniejszych chwilach.",
 "Światło księżyca oświetlało ich uśmiechy, gdy spacerowali po plaży pod rękę.",
 "Intymność była jak sekretne spotkanie dusz, które zjednoczone tworzyły jedność.",
 "Namiętność wypełniała ich serca, gdy zbliżali się coraz bardziej do siebie.",
 "Rozkosz rozkwitała w ich ciałach, dając im spełnienie i chwilowy spokój.",
 "Seksualna ekstaza wypełniała ich umysły, zatapiając w oceanie nieokiełznanej żądzy.",
 "Ich wspólne pragnienie wzrastało, rozpalając ogień nieokiełznanej namiętności.",
 "Nocne spotkanie było jak ukryty raj, gdzie ciało i dusza łączyły się w jedno.",
 "Pożądanie płonęło w ich oczach, gdy ich dłonie szukały dotyku i bliskości." , "Ich serca bijące w jednym rytmie, odkrywały magiczną siłę ich bliskości.",
 "Ciepło ich skór wypełniało każdą chwilę, tworząc niezatarte wspomnienia.",
 "Bliskość ich ciał była jak ukojenie dla dusz, które wędrowały w poszukiwaniu miłości.",
 "Delikatność ich dotyku mówiła więcej niż słowa, czyniąc każdy moment wyjątkowym.",
 "Intymna chwila przemieniła się w niezapomnianą opowieść o wzajemnym oddaniu.",
 "Ich bliskość była jak radość odkrywania drugiego człowieka na nowo, w każdej chwili.",
 "Ciepło ich serc było jak balsam dla dusz, które szukały spokoju i wspólnej harmonii.",
 "Bliskość ich dusz przemieniła się w namiętny taniec uczuć, który nigdy nie gasł.",
 "Pieszczoty i czułości, które dzieliły, były jak obietnice wierności na zawsze.",
 "Ich bliskość była jak twórczy akt miłości, malujący obrazy nieopisanego szczęścia." , "Ich czułe spojrzenia mówiły o miłości, która wzrastała z każdą chwilą.",
 "Czułość ich słów przemieniła się w pieśń miłości, śpiewaną w samo południe.",
 "Delikatność ich gestów była jak cicha modlitwa o wieczne błogosławieństwo.",
 "Czułość ich uśmiechów rozpalała serca, tworząc magiczną aurę ich związku.",
 "Miękkość ich głosów przemawiała do serc, budując mosty wzajemnego zrozumienia.",
 "Ich czułość była jak lekka melodia, która nie opuszczała ani na moment.",
 "Czułe słowa były jak opowieść o miłości, która rozkwitała w sercach na zawsze.",
 "Delikatność ich uczuć malowała barwne obrazy wspólnych chwil i wspomnień.",
 "Ich czułość była jak obietnica wierności, którą nosili w sercach przez całe życie.",
 "Delikatne pieszczoty były jak jasne gwiazdy na niebie, symbolizujące ich miłość." , "Ich dotyk był jak promień słońca, rozgrzewający serca i dusze.",
 "Ciepło ich dłoni wypełniało każdą chwilę, tworząc niezatarte wspomnienia.",
 "Dotyk ich skóry mówił więcej niż tysiąc słów, przemieniając chwilę w niezapomniany moment.",
 "Ciepło ich bliskości przemieniło się w magiczną opowieść o wzajemnym oddaniu.",
 "Ich dotyk był jak muzyka, która grała w takt ich serc.",
 "Intymność ich ciał była jak balsam dla dusz, które pragnęły jedności i spokoju.",
 "Ciepło ich dotyku było jak blask księżyca, oświetlający drogę do ich wspólnej przyszłości.",
 "Ich dłonie splatały się w milczeniu, mówiąc więcej niż tysiąc słów o miłości.",
 "Dotyk ich serc przemienił się w namiętny taniec uczuć, który nigdy nie gasł.",
 "Ciepło ich dotyku było jak obietnica, która trwała przez wieczne czasy." , "Dreszcz emocji przeszedł przez ich ciała, gdy spojrzenia się zetknęły.",
 "Przepełnieni emocjami, dreszcz przebiegł ich ciała, jakby czuli miłość na nowo.",
 "Koszmarne wspomnienia wywołały dreszcze na ich skórze, ale wspólnie je przezwyciężyli.",
 "Dreszcz przebiegł ich ciała, gdy pierwszy raz dotknęli się w milczeniu.",
 "Dreszcz adrenaliny wypełnił ich umysły, gdy zbliżali się do nieznanej przyszłości.",
 "Dreszcz podniecenia ożywił ich ciała, gdy ich spojrzenia się zetknęły."],
 "Biografia": [
      "Napoleon Bonaparte urodził się 15 sierpnia 1769 roku na Korsyce.",
        "Pochodził z rodziny szlacheckiej o włoskich korzeniach.",
        "W młodości wstąpił do armii francuskiej i ukończył szkołę militarną w Paryżu.",
        "Rozpoczął jako oficer artylerii, co wpłynęło na jego późniejsze zainteresowania reformami w armii.",
        "Po wybuchu rewolucji francuskiej poparł rewolucjonistów i odniósł sukcesy wojenne we Włoszech przeciwko Austriakom.",
        "W 1798 roku został wysłany do Egiptu, gdzie również odniósł sukcesy militarne.",
        "Po zamachu stanu 18 Brumaire'a (1799) objął władzę jako Pierwszy Konsul Francji.",
        "W 1804 roku koronował się na cesarza Francuzów, zakładając I Cesarstwo Francuskie.",
        "W latach 1805–1809 prowadził serie wojen przeciwko koalicjom europejskim, rozszerzając swoje wpływy na całą Europę.",
        "W 1812 roku doznał klęski w wojnie z Rosją, co doprowadziło do zawiązania VI koalicji antynapoleońskiej.",
        "Józef Klemens Piłsudski przyszedł na świat 5 grudnia 1867 roku w Zułowie na Litwie.",
        "Jego dzieciństwo spędził w Zułowie, w rodzinie o korzeniach szlacheckich.",
        "W młodości przeniósł się z rodziną do Wilna, gdzie rozpoczął naukę w rosyjskim gimnazjum.",
        "Wisława Szymborska urodziła się w 1923 roku w Kórniku koło Poznania.",
        "Od 1931 roku mieszkała w Krakowie.",
        "Studiowała polonistykę i socjologię na Uniwersytecie Jagiellońskim.",
        "W latach 1953-1966 była kierownikiem działu poezji w tygodniku „Życie literackie”.",
        "W latach 1967–1981 publikowała w tym tygodniku felietony Lektury nadobowiązkowe.",
        "Debiutowała w 1945 roku wierszem „Szukam słowa”.",
        "W pierwszych dwóch tomikach podejmowała tematy polityczno-publicystyczne.",
        "W 1956 roku wydała tom poetycki „Wołanie do Yeti”.",
        "Przez kolejne lata wydała m.in. takie tomiki jak: „Sól” (1962), „Sto pociech” (1967), „Wszelki wypadek” (1972), „Wielka liczba” (1976), „Ludzie na moście” (1986), „Koniec i początek” (1993) oraz „Chwila” (2002).",
        "W sumie wydała kilkanaście tomów poezji.",
        "Pisywała także felietony o książkach do różnych czasopism oraz tłumaczyła poezję, głównie francuską.",
        "W 1996 roku otrzymała Nagrodę Nobla za poezję, która z ironiczną precyzją pozwala historycznemu i biologicznemu kontekstowi ukazać się we fragmentach ludzkiej rzeczywistości.",
        "Zmarła w 2012 roku.",
        "Jako działacz socjalistyczny brał udział w zamachach na cara Aleksandra III.",
        "Za udział w spisku został skazany na pięć lat zsyłki na Syberii.",
        "Po powrocie do Wilna w 1892 roku, kontynuował działalność polityczną w szeregach socjalistów.",
        "W 1899 roku ożenił się z Marią Juszkiewiczową, a w 1900 roku oboje zostali osadzeni w Cytadeli warszawskiej.",
        "Po ucieczce przed rosyjską policją, kontynuował pracę konspiracyjną i organizowanie zamachów.",
        "Uważał Imperium Rosyjskie za głównego wroga Polski i działał na rzecz niepodległości kraju.",
        "Podczas I wojny światowej tworzył Legiony Polskie, walczące u boku państw centralnych.",
        "Po odzyskaniu niepodległości w 1918 roku, został Naczelnikiem Państwa Polskiego.",
        "Jego największym sukcesem militarnym była Bitwa Warszawska w 1920 roku, znana jako Cud nad Wisłą.",
        "Zmarł 12 maja 1935 roku, będąc ważną postacią w historii Polski.",
        "Życie osobiste było pełne wyzwań, ale znalazł stabilność w swojej rodzinie i pracy twórczej.",
        "Po przejściu na emeryturę poświęcił się nauczaniu młodych talentów, dzieląc się swoją wiedzą i doświadczeniem.",
        "Jego praca była ceniona nie tylko w kraju, ale także za granicą, gdzie otrzymał wiele nagród za swoje osiągnięcia.",
        "Zmarł w wieku 85 lat, pozostawiając po sobie trwały ślad w świecie literatury i kultury.",
        "Jego życiorys jest świadectwem determinacji i pasji, które prowadziły go przez całe życie.",
        "Przez całe życie pozostał wierny swoim wartościom i zasadom, co było fundamentem jego sukcesu zawodowego i osobistego.",
        "Jego historia jest inspiracją dla młodych pokoleń, zachęcając ich do dążenia do własnych marzeń i celów."
    ],   "kryminał": ["Detektyw wpadł na trop, który mógł doprowadzić do rozwiązania największej sprawy w swojej karierze.",
        "Na ścianie pomieszczenia zbrodni pojawiły się nieczytelne symbole, które mogły być kluczem do rozwiązania zagadki.",
        "Odkrycie nowego świadka zmieniło bieg śledztwa, otwierając zupełnie nowe możliwości w śledztwie.",
        "Mroczne sekrety rodzinne wydobywały się na światło dzienne, rzucając cień podejrzeń na najbliższych ofiary.",
        "Ciało zostało znalezione na podłodze sklepu, książki były rozrzucone po całym pomieszczeniu.",
       "Nie znaleziono fizycznej broni zbrodni, jednak zabójstwo zostało popełnione w wyniku staranek fizycznych.",
     "Samuel Turner wpadł w długi i potrzebował pilnie pieniędzy, co skłoniło go do zbrodni.",
     "Edward Finch, znany lokalny księgarz, padł ofiarą morderstwa w swoim sklepie z używanymi książkami.",
        "Edward Finch, 65-letni księgarz znany w Willow Creek, został znaleziony martwy w swoim sklepie.",
      "Mężczyzna nie miał wrogów i prowadził spokojne życie, co czyniło go niewidocznym celem dla przestępców.",
   "Początkowo niewinny zbieg okoliczności zaczął nabierać cech złożonego spisku, gdy detektyw zagłębiał się w szczegóły sprawy.",
        "Przesłuchanie podejrzanego przyniosło tylko kolejne pytania, zamiast odpowiedzi na kluczowe pytania w śledztwie.",
        "Stary, zakurzony dokument w archiwum okazał się kluczem do odnalezienia ukrytej prawdy o przeszłości ofiary.",
        "W mrocznym zaułku detektyw natrafił na tajemniczą postać, która mogła mieć kluczowe informacje na temat morderstwa.",
        "Za każdym zakrętem losów tej sprawy kryły się nowe niespodzianki, które komplikowały dochodzenie.",
        "Rozgrywka między detektywem a mordercą stawała się coraz bardziej złożona, gdy obie strony podchodziły do decydującego starcia.",
        "Wątek korupcji w policji zaczął wyłaniać się na pierwszy plan, zagrażając całemu śledztwu i sprawiedliwości.",
        "Zakulisowe gry polityczne okazały się kluczem do rozwiązania zagadki, rzucając światło na motywy kryminalne.",
        "Na granicy miasta odkryto ciało, które nie pasowało do typowego wzorca morderstwa, stawiając detektywa przed nowym wyzwaniem.",
        "W chwili przełomu detektyw odkrył, że prawdziwy sprawca był obecny na miejscu zbrodni od samego początku.",
        "Po latach milczenia świadek wreszcie zdecydował się zeznać, odsłaniając skrywaną przez lata prawdę o zbrodni.",
        "Mroczny zaułek, gdzie dochodziło do tajemniczych spotkań między gangsterami.",
        "Komisarz policji patrzył na zmasakrowane ciało, próbując odkryć, kto mógł być sprawcą tego okrutnego morderstwa.",
        "Tajemnicza notatka pozostawiona na miejscu zbrodni była jedynym tropem, jaki detektyw miał w tej sprawie.",
        "Skradziony diament wart miliony dolarów zniknął bez śladu, pozostawiając detektywa z zagadką do rozwiązania.",
        "Księgowy okradł firmę, fałszując dokumenty i transferując pieniądze na swoje konto offshore.",
        "Agentka specjalna pod przykrywką wkroczyła do podziemnego kasyna, próbując zdobyć informacje o handlu bronią.",
        "Podejrzany milioner, z reputacją czystą jak łza, ukrywał mroczne sekrety, które mogły zniszczyć jego karierę.",
        "Detektyw prowadził śledztwo w sprawie serii porwań, które wstrząsnęły spokojnym miastem.",
        "Za drzwiami starego domu kryły się sekrety, których odkrycie mogło zmienić losy całego miasta.",
        "Na ulicach miasta grasował seryjny morderca, wybierający swoje ofiary w sposób zupełnie przypadkowy.",
        "Złodziej opanował sztukę włamania, pozostawiając ślady tylko dla tych, którzy potrafią czytać między wierszami.",
        "Dawne zdjęcie odkryte w starym pudełku prowadziło do rozwiązania zagadki sprzed lat.",
        "Agent FBI śledził trop znikających świadków, którzy byli kluczowi w rozpracowaniu kartelu narkotykowego.",
        "Tajemniczy kasynowy krupier był w rzeczywistości szefem mafijnego syndykatu, kontrolującego cały przemyt w mieście.",
        "Pocisk znajdujący się na miejscu zbrodni wskazywał na to, że ofiara mogła być zamieszana w nielegalne interesy.",
        "Pośród cichych uliczek starego miasta, szeptane były tajemnice, które z czasem wyszły na jaw."

    ] , "humor": [
          'śmieszny', 'błyskotliwy', 'niezdarny', 'fajtłapa', 'mamusia', 'baba',          'dowcip', 'Jaś', 'głupi', 'szalony', 'zabawny', 'komiczny', 'przygłupi'      ] ,
        
    "reportaż": [
        "W małym miasteczku, życie toczyło się spokojnie aż do dnia, kiedy odkryto skandal korupcyjny w lokalnym ratuszu.",
        "Do sprawy w mediach społecznościowych odniósł się były prezes Orlenu, a obecnie europoseł Daniel Obajtek.",
        "Dokumenty ujawnione przez informatora rzucają nowe światło na zaniedbania w lokalnym systemie opieki zdrowotnej.",
        "Tymczasem Borys Budka odpowiedzialny za paraliż decyzyjny w spółkach energetycznych jest już w Brukseli, a tzw. wolne media, zamiast pytać o konkretne rozwiązania, wolą uczestniczyć w politycznej nagonce.",
       "Siłom ukraińskim udało się zatrzymać ofensywę armii rosyjskiej pod Charkowem.",
        "W obwodzie donieckim Rosjanie przedarli się przez obronę i ruszyli w stronę granic administracyjnych regionu.",
        "Urzędnik NATO ujawnił, że straty Rosji podczas ofensywy w obwodzie charkowskim były 'astronomiczne'.",
        "Rosyjska ofensywa w obwodzie charkowskim wyraźnie wyhamowała po zmobilizowaniu ukraińskich rezerw.",
        "Trwają walki o miasto Wowczańsk, położone ponad 70 kilometrów od Charkowa.",
        "Jeszcze do niedawna linia frontu w Wowczańsku przebiegała wzdłuż rzeki Wowczy, dzielącej miasto na pół.",
        "Siły ukraińskie odbiły kilka dzielnic Wowczańska, odpierając oddziały rosyjskie.",
        "Według naczelnego dowódcy ukraińskich sił zbrojnych Ołeksandra Syrskiego, armia rosyjska w Wowczańsku najwyraźniej 'ugrzęzła'.",
        "W obwodzie donieckim ich ofensywa się rozwija, szczególnie na odcinku pokrowskim.",
        "Największego przełomu armia rosyjska dokonała na kierunku strategicznie ważnego miasta Pokrowsk.",
        "Od lutego wojska rosyjskie przesunęły się o 20 kilometrów na kierunku Pokrowska.",
        "Rosjanie okupują wioskę Oczeretyne, co umożliwiło im szybki postęp w obwodzie donieckim.",
        "Wojska rosyjskie zbliżają się do wioski Wozdwiżenka, co może postawić siły ukraińskie w trudnej sytuacji.",
        "Nie ulega wątpliwości, że temat lanego poniedziałku wywołał liczne komentarze i wątpliwości, zarówno po stronie amatorów tego tradycyjnego polskiego obrzędu, jak i po stronie bełchatowian obawiających się o swoje bezpieczeństwo.",
        "Straty Rosji podczas majowej ofensywy w obwodzie charkowskim były 'astronomiczne'.",
        "Na całym świecie rozpoczęto masowe kampanie szczepień, priorytetowo traktując pracowników służby zdrowia, osoby starsze i populacje narażone.",
        "W poprzednim miesiącu armia rosyjska prawdopodobnie ponosiła straty w wysokości prawie tysiąca zabitych żołnierzy dziennie.",
        "Raporty sztabu generalnego ukraińskich sił zbrojnych mówią, że dziennie straty Rosjan przekraczają tysiąc żołnierzy.",
        "Denys Prokopenko, dowódca brygady Azow, podziękował administracji prezydenta USA Joe Bidena za zniesienie zakazu dostarczania broni.",
        "Brygada Azow jest uważana za jedną z najlepszych ukraińskich jednostek bojowych.",
        "Zakazano jej używania amerykańskiej broni, ponieważ niektórzy założyciele Azowa głosili rasistowskie i ksenofobiczne poglądy.",
        "Prezydent Ukrainy Wołodymyr Zełenski spotkał się z przywódcami państw G7.",
        "Zełenski podpisał z prezydentem USA Joe Bidenem dwustronną umowę o bezpieczeństwie.",
        "Umowa określa wsparcie Stanów Zjednoczonych do czasu zwycięstwa Ukrainy w wojnie.",
        "Japonia podpisała z Ukrainą porozumienie dotyczące wsparcia i pomocy.",
        "Przywódcy państw G7 zdecydowali o wypłacie Kijowowi 50 miliardów dolarów.",
        "W Szwajcarii rozpoczął się dwudniowy szczyt pokojowy w sprawie Ukrainy.",
        "Przedstawiciele ponad stu państw i organizacji biorą udział w szczycie pokojowym.",
        "Rosja nie została zaproszona do udziału w spotkaniu w Szwajcarii.",
        "Święto to jest, co prawda, uświęcone tradycją, jednakże są ludzie, którzy zdecydowanie przesadzają z hołdowaniem tej jednej tradycji",
        "Szczyt ma na celu określenie planu działania dotyczącego przyszłego procesu pokojowego.",
        "To tutaj odbywa się coroczny Festiwal Tańca i Muzyki Ludowej, który przyciąga tłumy widzów oraz tancerzy i muzyków z całej Polski.",
        "Uciekinierzy przekroczyli granicę w okolicach ukraińsko-węgierskiego przejścia granicznego Kosyno-Barabasi.",
        "Wicepremier Węgier Zsolt Semjen oznajmił, że uchodźcy nie zostaną odesłani na Ukrainę.",
        "Kolejnych 40 mężczyzn z Ukrainy próbowało przekroczyć granicę z Mołdawią.",
        "Zostali zatrzymani przez ukraińską straż graniczną w obwodzie odeskim.",
        "Kierowca ciężarówki deklarował, że przewozi ziarno.",
        "Siły ukraińskie przeprowadziły skuteczne kontrataki w obwodzie charkowskim.",
        "Wojska rosyjskie zbliżają się do strategicznie ważnych obszarów w Donbasie.",
        "Armia ukraińska odzyskała pozycje w pobliżu wioski Łypci.",
        "Ukraińscy żołnierze walczą z oddziałami rosyjskimi w różnych regionach kraju.",
        "Administracja prezydenta USA podjęła decyzję o wsparciu wojskowym dla Ukrainy.",
        "Brygada Azow znana jest z długotrwałej obrony zakładów Azowstal w Mariupolu.",
        "Prezydent Zełenski dąży do integracji Ukrainy z NATO.",
        "Szwajcarski rząd zorganizował szczyt pokojowy, aby wspierać proces pokojowy.",
        "Uciekinierzy z Ukrainy szukają schronienia w krajach sąsiednich.",
        "Agresywne testowanie i efektywny system śledzenia kontaktów w Korei Południowej stały się wzorem dla innych.",
        "Trwają walki o kontrolę nad kluczowymi miastami w Ukrainie.",
        "Raporty ukraińskiego sztabu generalnego wskazują na wysokie straty rosyjskie.",
        "Siły ukraińskie przygotowują się do dalszych kontrataków.",
        "Ukraińskie rezerwy zostały zmobilizowane do walki z rosyjską ofensywą.",
        "Walki o miasto Wowczańsk wciąż trwają, a siły ukraińskie odpierają ataki.",
        "Relacje z demonstracji w stolicy ukazują napiętą atmosferę i determinację protestujących.",
        "Kraje takie jak Izrael i Stany Zjednoczone przodowały w wskaźnikach szczepień, co skutkowało znacznym spadkiem liczby przypadków i hospitalizacji.",
        "Na drugim miejscu jest Jacek Siewiera (10,4 proc.), szef Biura Bezpieczeństwa Narodowego.",
        "Badanie wpływu zanieczyszczenia powietrza na zdrowie mieszkańców ujawnia alarmujące fakty.",
        "Historie ludzi walczących z uzależnieniami pokazują siłę i determinację w dążeniu do zdrowia.",
        "Choć nie jest prezesem płockiego koncernu od lutego, nie ustają kontrowersje wokół podejmowanych za jego kadencji decyzji."
    ]}  
